language: node_js
node_js:
  -"6.13.0"

services:
  - docker

before_install:
  - npm i -g npm@6.13.0

after_deploying:
  - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ca-central-1"  
  app: "elastic-beanstalk-tutorial"
  env: "elastic-beanstalk-tutorial-dev"
  bucket_name: "elasticbeanstalk-ca-central-1-882371129764"
  on:
    branch: master
